version: "3"

services:
  mosquitto:
    image: eclipse-mosquitto:2
    container_name: mosquitto
    volumes:
      - ./mosquitto/config:/mosquitto/config
      - ./mosquitto/data:/mosquitto/data
      - ./mosquitto/log:/mosquitto/log
    ports:
      - "1883:1883"
      - "9001:9001"

  mqtt-logger:
    build: ./mqtt-logger
    container_name: mqtt-logger
    depends_on:
      - mosquitto
    ports:
      - "5000:5000"
    volumes:
      - ./mqtt-logger:/app
    working_dir: /app
    command: python app.py

  vue-app:
    build: ./vue-app
    container_name: vue-app
    depends_on:
      - mqtt-logger
    volumes:
      - ./vue-app:/app 
      - /app/node_modules 
    ports:
      - "5173:5173"
    stdin_open: true
    tty: true
    working_dir: /app
    command: npm run dev -- --host 0.0.0.0 --port 5173
    environment:
      - VITE_API_URL=http://localhost:5000

